name: Build and Test

on: [push, pull_request]

jobs:

  test-windows-x64:
    needs: test-alpine-x64
    runs-on: windows-2022
    steps:
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x
    - name: Install workloads
      run: dotnet workload install ios tvos maccatalyst
    - run: dotnet --info
    - uses: actions/checkout@v4
    - name: Test (.NET 9.0/Debug)
      run: dotnet test -f net9.0 -c Debug
    - name: Test (.NET 9.0/Release)
      run: dotnet test -f net9.0 -c Release
    - name: Test (.NET 8.0/Debug)
      run: dotnet test -f net8.0 -c Debug
    - name: Test (.NET 8.0/Release)
      run: dotnet test -f net8.0 -c Release
    - name: Pack
      run: dotnet pack -c Release
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: '**/*.nupkg'

  test-ubuntu-x64:
    needs: test-macos-arm64
    runs-on: ubuntu-latest
    steps:
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x
    - run: dotnet --info
    - uses: actions/checkout@v4
    - name: Test (.NET 9.0/Debug)
      run: dotnet test -f net9.0 -c Debug
    - name: Test (.NET 9.0/Release)
      run: dotnet test -f net9.0 -c Release
    - name: Test (.NET 8.0/Debug)
      run: dotnet test -f net8.0 -c Debug
    - name: Test (.NET 8.0/Release)
      run: dotnet test -f net8.0 -c Release

  test-alpine-x64:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:9.0-alpine
    steps:
    - run: dotnet --info
    - uses: actions/checkout@v4
    - name: Test (.NET 9.0/Debug)
      run: dotnet test -f net9.0 -c Debug
    - name: Test (.NET 9.0/Release)
      run: dotnet test -f net9.0 -c Release

  test-macos-arm64:
    needs: test-windows-x64
    runs-on: macos-latest
    steps:
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x
    - run: dotnet --info
    - uses: actions/checkout@v4
    - name: Test (.NET 9.0/Debug)
      run: dotnet test -f net9.0 -c Debug
    - name: Test (.NET 9.0/Release)
      run: dotnet test -f net9.0 -c Release
    - name: Test (.NET 8.0/Debug)
      run: dotnet test -f net8.0 -c Debug
    - name: Test (.NET 8.0/Release)
      run: dotnet test -f net8.0 -c Release
